// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { createRequire } = require('node:module')
require = createRequire(__filename)

const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (typeof process.report?.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      nativeBinding = require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./chia-wallet-sdk.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-android-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm') {
      try {
        return require('./chia-wallet-sdk.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-android-arm-eabi')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      try {
        return require('./chia-wallet-sdk.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-win32-x64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'ia32') {
      try {
        return require('./chia-wallet-sdk.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-win32-ia32-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('./chia-wallet-sdk.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-win32-arm64-msvc')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
        return require('./chia-wallet-sdk.darwin-universal.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-darwin-universal')
      } catch (e) {
        loadErrors.push(e)
      }

    if (process.arch === 'x64') {
      try {
        return require('./chia-wallet-sdk.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-darwin-x64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('./chia-wallet-sdk.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-darwin-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./chia-wallet-sdk.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-freebsd-x64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 'arm64') {
      try {
        return require('./chia-wallet-sdk.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-freebsd-arm64')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
        return require('./chia-wallet-sdk.linux-x64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-x64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./chia-wallet-sdk.linux-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-x64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
        return require('./chia-wallet-sdk.linux-arm64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-arm64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./chia-wallet-sdk.linux-arm64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-arm64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
        return require('./chia-wallet-sdk.linux-arm-musleabihf.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-arm-musleabihf')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./chia-wallet-sdk.linux-arm-gnueabihf.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-arm-gnueabihf')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
        return require('./chia-wallet-sdk.linux-riscv64-musl.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-riscv64-musl')
      } catch (e) {
        loadErrors.push(e)
      }

      } else {
        try {
        return require('./chia-wallet-sdk.linux-riscv64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-riscv64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./chia-wallet-sdk.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-ppc64-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

    } else if (process.arch === 's390x') {
      try {
        return require('./chia-wallet-sdk.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      try {
        return require('chia-wallet-sdk-linux-s390x-gnu')
      } catch (e) {
        loadErrors.push(e)
      }

    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

nativeBinding = requireNative()

if (!nativeBinding || process.env.NAPI_RS_FORCE_WASI) {
  try {
    nativeBinding = require('./chia-wallet-sdk.wasi.cjs')
  } catch (err) {
    if (process.env.NAPI_RS_FORCE_WASI) {
      loadErrors.push(err)
    }
  }
  if (!nativeBinding) {
    try {
      nativeBinding = require('chia-wallet-sdk-wasm32-wasi')
    } catch (err) {
      if (process.env.NAPI_RS_FORCE_WASI) {
        loadErrors.push(err)
      }
    }
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    throw new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
      { cause: loadErrors }
    )
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.Action = nativeBinding.Action
module.exports.AdditionsAndRemovalsResponse = nativeBinding.AdditionsAndRemovalsResponse
module.exports.Address = nativeBinding.Address
module.exports.AggSigAmount = nativeBinding.AggSigAmount
module.exports.AggSigMe = nativeBinding.AggSigMe
module.exports.AggSigParent = nativeBinding.AggSigParent
module.exports.AggSigParentAmount = nativeBinding.AggSigParentAmount
module.exports.AggSigParentPuzzle = nativeBinding.AggSigParentPuzzle
module.exports.AggSigPuzzle = nativeBinding.AggSigPuzzle
module.exports.AggSigPuzzleAmount = nativeBinding.AggSigPuzzleAmount
module.exports.AggSigUnsafe = nativeBinding.AggSigUnsafe
module.exports.AssertBeforeHeightAbsolute = nativeBinding.AssertBeforeHeightAbsolute
module.exports.AssertBeforeHeightRelative = nativeBinding.AssertBeforeHeightRelative
module.exports.AssertBeforeSecondsAbsolute = nativeBinding.AssertBeforeSecondsAbsolute
module.exports.AssertBeforeSecondsRelative = nativeBinding.AssertBeforeSecondsRelative
module.exports.AssertCoinAnnouncement = nativeBinding.AssertCoinAnnouncement
module.exports.AssertConcurrentPuzzle = nativeBinding.AssertConcurrentPuzzle
module.exports.AssertConcurrentSpend = nativeBinding.AssertConcurrentSpend
module.exports.AssertEphemeral = nativeBinding.AssertEphemeral
module.exports.AssertHeightAbsolute = nativeBinding.AssertHeightAbsolute
module.exports.AssertHeightRelative = nativeBinding.AssertHeightRelative
module.exports.AssertMyAmount = nativeBinding.AssertMyAmount
module.exports.AssertMyBirthHeight = nativeBinding.AssertMyBirthHeight
module.exports.AssertMyBirthSeconds = nativeBinding.AssertMyBirthSeconds
module.exports.AssertMyCoinId = nativeBinding.AssertMyCoinId
module.exports.AssertMyParentId = nativeBinding.AssertMyParentId
module.exports.AssertMyPuzzleHash = nativeBinding.AssertMyPuzzleHash
module.exports.AssertPuzzleAnnouncement = nativeBinding.AssertPuzzleAnnouncement
module.exports.AssertSecondsAbsolute = nativeBinding.AssertSecondsAbsolute
module.exports.AssertSecondsRelative = nativeBinding.AssertSecondsRelative
module.exports.BlockchainState = nativeBinding.BlockchainState
module.exports.BlockchainStateResponse = nativeBinding.BlockchainStateResponse
module.exports.BlockRecord = nativeBinding.BlockRecord
module.exports.BlsPair = nativeBinding.BlsPair
module.exports.BlsPairWithCoin = nativeBinding.BlsPairWithCoin
module.exports.Bulletin = nativeBinding.Bulletin
module.exports.BulletinMessage = nativeBinding.BulletinMessage
module.exports.Cat = nativeBinding.Cat
module.exports.CatInfo = nativeBinding.CatInfo
module.exports.CatSpend = nativeBinding.CatSpend
module.exports.Certificate = nativeBinding.Certificate
module.exports.ChallengeChainSubSlot = nativeBinding.ChallengeChainSubSlot
module.exports.Clawback = nativeBinding.Clawback
module.exports.ClawbackV2 = nativeBinding.ClawbackV2
module.exports.Clvm = nativeBinding.Clvm
module.exports.Coin = nativeBinding.Coin
module.exports.CoinRecord = nativeBinding.CoinRecord
module.exports.CoinsetClient = nativeBinding.CoinsetClient
module.exports.CoinSpend = nativeBinding.CoinSpend
module.exports.CoinState = nativeBinding.CoinState
module.exports.CoinStateFilters = nativeBinding.CoinStateFilters
module.exports.CoinStateUpdate = nativeBinding.CoinStateUpdate
module.exports.CommitmentSlot = nativeBinding.CommitmentSlot
module.exports.Connector = nativeBinding.Connector
module.exports.Constants = nativeBinding.Constants
module.exports.CreateCoin = nativeBinding.CreateCoin
module.exports.CreateCoinAnnouncement = nativeBinding.CreateCoinAnnouncement
module.exports.CreatedBulletin = nativeBinding.CreatedBulletin
module.exports.CreatedDid = nativeBinding.CreatedDid
module.exports.CreatePuzzleAnnouncement = nativeBinding.CreatePuzzleAnnouncement
module.exports.CurriedProgram = nativeBinding.CurriedProgram
module.exports.Delta = nativeBinding.Delta
module.exports.Deltas = nativeBinding.Deltas
module.exports.Did = nativeBinding.Did
module.exports.DidInfo = nativeBinding.DidInfo
module.exports.DropCoin = nativeBinding.DropCoin
module.exports.EndOfSubSlotBundle = nativeBinding.EndOfSubSlotBundle
module.exports.EntrySlot = nativeBinding.EntrySlot
module.exports.Event = nativeBinding.Event
module.exports.FinishedSpends = nativeBinding.FinishedSpends
module.exports.Foliage = nativeBinding.Foliage
module.exports.FoliageBlockData = nativeBinding.FoliageBlockData
module.exports.FoliageTransactionBlock = nativeBinding.FoliageTransactionBlock
module.exports.Force1Of2RestrictedVariableMemo = nativeBinding.Force1Of2RestrictedVariableMemo
module.exports.Force1of2RestrictedVariableMemo = nativeBinding.Force1of2RestrictedVariableMemo
module.exports.FullBlock = nativeBinding.FullBlock
module.exports.GetBlockRecordResponse = nativeBinding.GetBlockRecordResponse
module.exports.GetBlockRecordsResponse = nativeBinding.GetBlockRecordsResponse
module.exports.GetBlockResponse = nativeBinding.GetBlockResponse
module.exports.GetBlockSpendsResponse = nativeBinding.GetBlockSpendsResponse
module.exports.GetBlocksResponse = nativeBinding.GetBlocksResponse
module.exports.GetCoinRecordResponse = nativeBinding.GetCoinRecordResponse
module.exports.GetCoinRecordsResponse = nativeBinding.GetCoinRecordsResponse
module.exports.GetMempoolItemResponse = nativeBinding.GetMempoolItemResponse
module.exports.GetMempoolItemsResponse = nativeBinding.GetMempoolItemsResponse
module.exports.GetNetworkInfoResponse = nativeBinding.GetNetworkInfoResponse
module.exports.GetPuzzleAndSolutionResponse = nativeBinding.GetPuzzleAndSolutionResponse
module.exports.Id = nativeBinding.Id
module.exports.InfusedChallengeChainSubSlot = nativeBinding.InfusedChallengeChainSubSlot
module.exports.InnerPuzzleMemo = nativeBinding.InnerPuzzleMemo
module.exports.IntermediaryCoinProof = nativeBinding.IntermediaryCoinProof
module.exports.K1Pair = nativeBinding.K1Pair
module.exports.K1PublicKey = nativeBinding.K1PublicKey
module.exports.K1SecretKey = nativeBinding.K1SecretKey
module.exports.K1Signature = nativeBinding.K1Signature
module.exports.LineageProof = nativeBinding.LineageProof
module.exports.MedievalVault = nativeBinding.MedievalVault
module.exports.MedievalVaultHint = nativeBinding.MedievalVaultHint
module.exports.MedievalVaultInfo = nativeBinding.MedievalVaultInfo
module.exports.MeltSingleton = nativeBinding.MeltSingleton
module.exports.MemberConfig = nativeBinding.MemberConfig
module.exports.MemberMemo = nativeBinding.MemberMemo
module.exports.MemoKind = nativeBinding.MemoKind
module.exports.MempoolItem = nativeBinding.MempoolItem
module.exports.MempoolMinFees = nativeBinding.MempoolMinFees
module.exports.MetadataUpdate = nativeBinding.MetadataUpdate
module.exports.MintedNfts = nativeBinding.MintedNfts
module.exports.MipsMemo = nativeBinding.MipsMemo
module.exports.MipsMemoContext = nativeBinding.MipsMemoContext
module.exports.MipsSpend = nativeBinding.MipsSpend
module.exports.Mnemonic = nativeBinding.Mnemonic
module.exports.MofNMemo = nativeBinding.MofNMemo
module.exports.NewPeakWallet = nativeBinding.NewPeakWallet
module.exports.Nft = nativeBinding.Nft
module.exports.NftInfo = nativeBinding.NftInfo
module.exports.NftLauncherProof = nativeBinding.NftLauncherProof
module.exports.NftMetadata = nativeBinding.NftMetadata
module.exports.NftMint = nativeBinding.NftMint
module.exports.NotarizedPayment = nativeBinding.NotarizedPayment
module.exports.OfferSecurityCoinDetails = nativeBinding.OfferSecurityCoinDetails
module.exports.OptionContract = nativeBinding.OptionContract
module.exports.OptionInfo = nativeBinding.OptionInfo
module.exports.OptionMetadata = nativeBinding.OptionMetadata
module.exports.OptionType = nativeBinding.OptionType
module.exports.OptionTypeCat = nativeBinding.OptionTypeCat
module.exports.OptionTypeNft = nativeBinding.OptionTypeNft
module.exports.OptionTypeRevocableCat = nativeBinding.OptionTypeRevocableCat
module.exports.OptionTypeXch = nativeBinding.OptionTypeXch
module.exports.OptionUnderlying = nativeBinding.OptionUnderlying
module.exports.Output = nativeBinding.Output
module.exports.Outputs = nativeBinding.Outputs
module.exports.P2ParentCoin = nativeBinding.P2ParentCoin
module.exports.P2ParentCoinChildParseResult = nativeBinding.P2ParentCoinChildParseResult
module.exports.Pair = nativeBinding.Pair
module.exports.ParsedCat = nativeBinding.ParsedCat
module.exports.ParsedCatInfo = nativeBinding.ParsedCatInfo
module.exports.ParsedDid = nativeBinding.ParsedDid
module.exports.ParsedDidInfo = nativeBinding.ParsedDidInfo
module.exports.ParsedDidSpend = nativeBinding.ParsedDidSpend
module.exports.ParsedNft = nativeBinding.ParsedNft
module.exports.ParsedNftInfo = nativeBinding.ParsedNftInfo
module.exports.ParsedNftTransfer = nativeBinding.ParsedNftTransfer
module.exports.ParsedOption = nativeBinding.ParsedOption
module.exports.ParsedOptionInfo = nativeBinding.ParsedOptionInfo
module.exports.ParsedPayment = nativeBinding.ParsedPayment
module.exports.Payment = nativeBinding.Payment
module.exports.Peer = nativeBinding.Peer
module.exports.PeerOptions = nativeBinding.PeerOptions
module.exports.PendingSpend = nativeBinding.PendingSpend
module.exports.PoolTarget = nativeBinding.PoolTarget
module.exports.Program = nativeBinding.Program
module.exports.Proof = nativeBinding.Proof
module.exports.ProofOfSpace = nativeBinding.ProofOfSpace
module.exports.PublicKey = nativeBinding.PublicKey
module.exports.PushTxResponse = nativeBinding.PushTxResponse
module.exports.Puzzle = nativeBinding.Puzzle
module.exports.PuzzleSolutionResponse = nativeBinding.PuzzleSolutionResponse
module.exports.R1Pair = nativeBinding.R1Pair
module.exports.R1PublicKey = nativeBinding.R1PublicKey
module.exports.R1SecretKey = nativeBinding.R1SecretKey
module.exports.R1Signature = nativeBinding.R1Signature
module.exports.ReceiveMessage = nativeBinding.ReceiveMessage
module.exports.Remark = nativeBinding.Remark
module.exports.ReserveFee = nativeBinding.ReserveFee
module.exports.RespondCoinState = nativeBinding.RespondCoinState
module.exports.RespondPuzzleState = nativeBinding.RespondPuzzleState
module.exports.Restriction = nativeBinding.Restriction
module.exports.RestrictionMemo = nativeBinding.RestrictionMemo
module.exports.RewardChainBlock = nativeBinding.RewardChainBlock
module.exports.RewardChainSubSlot = nativeBinding.RewardChainSubSlot
module.exports.RewardDistributor = nativeBinding.RewardDistributor
module.exports.RewardDistributorCommitmentSlotValue = nativeBinding.RewardDistributorCommitmentSlotValue
module.exports.RewardDistributorConstants = nativeBinding.RewardDistributorConstants
module.exports.RewardDistributorEntrySlotValue = nativeBinding.RewardDistributorEntrySlotValue
module.exports.RewardDistributorFinishedSpendResult = nativeBinding.RewardDistributorFinishedSpendResult
module.exports.RewardDistributorInfoFromEveCoin = nativeBinding.RewardDistributorInfoFromEveCoin
module.exports.RewardDistributorInfoFromLauncher = nativeBinding.RewardDistributorInfoFromLauncher
module.exports.RewardDistributorInitiatePayoutResult = nativeBinding.RewardDistributorInitiatePayoutResult
module.exports.RewardDistributorLauncherSolutionInfo = nativeBinding.RewardDistributorLauncherSolutionInfo
module.exports.RewardDistributorLaunchResult = nativeBinding.RewardDistributorLaunchResult
module.exports.RewardDistributorNewEpochResult = nativeBinding.RewardDistributorNewEpochResult
module.exports.RewardDistributorRemoveEntryResult = nativeBinding.RewardDistributorRemoveEntryResult
module.exports.RewardDistributorRewardSlotValue = nativeBinding.RewardDistributorRewardSlotValue
module.exports.RewardDistributorStakeResult = nativeBinding.RewardDistributorStakeResult
module.exports.RewardDistributorState = nativeBinding.RewardDistributorState
module.exports.RewardDistributorUnstakeResult = nativeBinding.RewardDistributorUnstakeResult
module.exports.RewardDistributorWithdrawIncentivesResult = nativeBinding.RewardDistributorWithdrawIncentivesResult
module.exports.RewardSlot = nativeBinding.RewardSlot
module.exports.RoundRewardInfo = nativeBinding.RoundRewardInfo
module.exports.RoundTimeInfo = nativeBinding.RoundTimeInfo
module.exports.RunCatTail = nativeBinding.RunCatTail
module.exports.SecretKey = nativeBinding.SecretKey
module.exports.SendMessage = nativeBinding.SendMessage
module.exports.SettlementNftSpendResult = nativeBinding.SettlementNftSpendResult
module.exports.Signature = nativeBinding.Signature
module.exports.Simulator = nativeBinding.Simulator
module.exports.Softfork = nativeBinding.Softfork
module.exports.Spend = nativeBinding.Spend
module.exports.SpendBundle = nativeBinding.SpendBundle
module.exports.Spends = nativeBinding.Spends
module.exports.StreamedAsset = nativeBinding.StreamedAsset
module.exports.StreamedAssetParsingResult = nativeBinding.StreamedAssetParsingResult
module.exports.StreamingPuzzleInfo = nativeBinding.StreamingPuzzleInfo
module.exports.SubEpochSummary = nativeBinding.SubEpochSummary
module.exports.SubSlotProofs = nativeBinding.SubSlotProofs
module.exports.SyncState = nativeBinding.SyncState
module.exports.TradePrice = nativeBinding.TradePrice
module.exports.TransactionsInfo = nativeBinding.TransactionsInfo
module.exports.TransferNft = nativeBinding.TransferNft
module.exports.TransferNftById = nativeBinding.TransferNftById
module.exports.UpdateDataStoreMerkleRoot = nativeBinding.UpdateDataStoreMerkleRoot
module.exports.UpdateNftMetadata = nativeBinding.UpdateNftMetadata
module.exports.Vault = nativeBinding.Vault
module.exports.VaultInfo = nativeBinding.VaultInfo
module.exports.VaultMint = nativeBinding.VaultMint
module.exports.VaultSpendReveal = nativeBinding.VaultSpendReveal
module.exports.VaultTransaction = nativeBinding.VaultTransaction
module.exports.VdfInfo = nativeBinding.VdfInfo
module.exports.VDFInfo = nativeBinding.VDFInfo
module.exports.VdfProof = nativeBinding.VdfProof
module.exports.VDFProof = nativeBinding.VDFProof
module.exports.WrapperMemo = nativeBinding.WrapperMemo
module.exports.blsMemberHash = nativeBinding.blsMemberHash
module.exports.bulletinPuzzleHash = nativeBinding.bulletinPuzzleHash
module.exports.bytesEqual = nativeBinding.bytesEqual
module.exports.catPuzzleHash = nativeBinding.catPuzzleHash
module.exports.curryTreeHash = nativeBinding.curryTreeHash
module.exports.customMemberHash = nativeBinding.customMemberHash
module.exports.decodeOffer = nativeBinding.decodeOffer
module.exports.encodeOffer = nativeBinding.encodeOffer
module.exports.fixedMemberHash = nativeBinding.fixedMemberHash
module.exports.force1Of2Restriction = nativeBinding.force1Of2Restriction
module.exports.fromHex = nativeBinding.fromHex
module.exports.generateBytes = nativeBinding.generateBytes
module.exports.k1MemberHash = nativeBinding.k1MemberHash
module.exports.mOfNHash = nativeBinding.mOfNHash
module.exports.passkeyMemberHash = nativeBinding.passkeyMemberHash
module.exports.preventConditionOpcodeRestriction = nativeBinding.preventConditionOpcodeRestriction
module.exports.preventMultipleCreateCoinsRestriction = nativeBinding.preventMultipleCreateCoinsRestriction
module.exports.preventVaultSideEffectsRestriction = nativeBinding.preventVaultSideEffectsRestriction
module.exports.r1MemberHash = nativeBinding.r1MemberHash
module.exports.RestrictionKind = nativeBinding.RestrictionKind
module.exports.RewardDistributorType = nativeBinding.RewardDistributorType
module.exports.selectCoins = nativeBinding.selectCoins
module.exports.sha256 = nativeBinding.sha256
module.exports.singletonMemberHash = nativeBinding.singletonMemberHash
module.exports.standardPuzzleHash = nativeBinding.standardPuzzleHash
module.exports.timelockRestriction = nativeBinding.timelockRestriction
module.exports.toHex = nativeBinding.toHex
module.exports.TransferType = nativeBinding.TransferType
module.exports.treeHashAtom = nativeBinding.treeHashAtom
module.exports.treeHashPair = nativeBinding.treeHashPair
module.exports.UriKind = nativeBinding.UriKind
module.exports.wrappedDelegatedPuzzleHash = nativeBinding.wrappedDelegatedPuzzleHash
