[package]
name = "chia-sdk-derive"
version = "0.27.2"
edition = "2021"
license = "Apache-2.0"
description = "Derive macros for chia-sdk-types."
authors = ["Brandon Haggstrom <me@rigidnetwork.com>"]
homepage = "https://github.com/Rigidity/chia-wallet-sdk"
repository = "https://github.com/Rigidity/chia-wallet-sdk"
readme = { workspace = true }
keywords = { workspace = true }
categories = { workspace = true }

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["visit-mut", "extra-traits"] }
quote = { workspace = true }
convert_case = { workspace = true }
