name: WASM
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow_ref, github.event.pull_request.number) || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wasm
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: wasm/pnpm-lock.yaml
          architecture: x64

      - name: Install dependencies
        run: pnpm install

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install wasm-pack
        run: cargo install wasm-pack --locked

      - name: Tests
        run: pnpm test

      - name: WASM build and pack
        run: |
          rm -rf pkg
          wasm-pack build
          wasm-pack pack

      - name: Upload NPM pkg artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-pkg
          path: ./wasm/pkg/*-*.tgz

      - name: Ensure we have a new enough npm version for trusted publishing
        run: |
          npm install -g npm
          npm --version

      - name: Publish
        if: startsWith(github.event.ref, 'refs/tags')
        uses: JS-DevTools/npm-publish@v4
        with:
          provenance: true
          package: wasm/pkg/package.json
